spring:
  application:
      name: aiservice

  mongodb:
    ***REMOVED***
    database: airecommendationdb

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: activity-processor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.fitness.aiservice.model.Activity
        spring.json.trusted.package: "*"

kafka:
    topic:
      name: activity-events

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


gemini:
  api:
    uri: ${GEMINI_URI}
    key: ${GEMINI_KEY}



